package Euler1_50;

import java.util.ArrayList;
import java.util.HashSet;

/**
 * Pentagon numbers Problem 44 Pentagonal numbers are generated by the formula,
 * Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
 * of D?
 * 
 * @author Chjun-chi
 *
 */
public class PentagonNumbers {

	private static HashSet<Long> hSet = new HashSet<>();
	private static ArrayList<Long> array = new ArrayList<>();
	public static void main(String[] args) {
		pentagonNumbers();
		long d = Long.MAX_VALUE;
		for (int i = 0; i < array.size(); i++) {
			for (int j = 1; j < array.size(); j++) {
				if (array.get(i) != array.get(j)) {
					long p1 = Math.abs(array.get(i) - array.get(j));
					long p2 = array.get(i) + array.get(j);
					if (hSet.contains(p1) && hSet.contains(p2)) {
						if (p1 < d) {
							d = p1;
							System.out.println(array.get(i) +" - "+ array.get(j));
							System.out.println(d);
						}
					}
				}
			}
		}
		System.out.println("D = " + d);
	}

	public static void pentagonNumbers() {

		for (int n = 1; n < 10000; n++) {
			long p = (n * (3 * n - 1)) / 2;
			hSet.add(p);
			array.add(p);

		}
	}

}
